### ISSUE TITLE
[Question] File name storychief / craft

### ISSUE THREAD

**Issue by umkasanki** [Story-Chief/craft-cms-module-storychief-v3#10]
When uploading a image on storychief, the file name in Craft CMS is adding a strange code behind the regular file name. Can we keep the original file name (for SEO purpose)? 
Thanks

![Schermafbeelding 2022-05-10 om 11 59 33](https://user-images.githubusercontent.com/496132/168049898-007d0144-8c71-4ce6-b085-7eb15fc08158.png)

**Comment by sweet-greg** [comment]
Hi, that's not something this plugin is doing, but StoryChief itself.
As for SEO implications, search engines don't tend to care about random suffixes in the file name, they are smart enough to ignore these.
