### ISSUE TITLE
Craft 4 version

### ISSUE THREAD

**Issue by justinholtweb** [Story-Chief/craft-cms-module-storychief-v3#12]
Do you have plans to create a Craft 4 compatible version of this plugin?

**Comment by umkasanki** [comment]
> Do you have plans to create a Craft 4 compatible version of this plugin?

https://github.com/Story-Chief/craft-cms-module-storychief/issues/3 
:slightly_smiling_face:

**Comment by SkermBE** [comment]
We are also looking for a Craft 4 version, any update on this?

**Comment by gregory-claeyssens** [comment]
Very late to the party, but the version 4 has been available for a w hile now right here: https://github.com/Story-Chief/craft-cms-module-storychief-v3/tree/craft-cms-4
