### ISSUE TITLE
Further development of this plugin for v4 and v5 ?

### ISSUE THREAD

**Issue by delixyr** [Story-Chief/craft-cms-module-storychief-v3#16]
Is this plugin being developed for newer versions of craftcms? v% got released recently. You are still on v3.

**Comment by gregory-claeyssens** [comment]
@delixyr Support for v4 was already there, but on a different branch, it wasn't clear at all.
We updated the readme so it should be clearer.
Craft5 support was also added.
Thank you for flagging
