### ISSUE TITLE
Support for Redactor fields?

### ISSUE THREAD

**Issue by justinholtweb** [Story-Chief/craft-cms-module-storychief-v3#7]
Can you possibly add support for importing into Craft Redactor fields? Currently only being able to import text content into plaintext fields causes loss of heading structures created in Storychief editor.

**Comment by sweet-greg** [comment]
Hi Justin.
We're not oppossed to adding support for redactor fieds. 
A PR could really get the balling rolling on this though.

**Comment by sweet-greg** [comment]
Hi @justinholtweb support has been added with v1.0.10.
